hospitalapp/urls.py
from django.urls import path
from .views import *

app_name = 'hospitalapp'
urlpatterns = [
    # clients
#     path('', HomeView.as_view(), name="index"),
    path('', HomeView, name="index"),
    path('recommend-doctor/', RecommendDoctorView.as_view(), name="recommend"),
    path('cliendhome', ClientHomeView.as_view(), name="clienthome"),
    path('my-loc/', ClientLocationView.as_view(), name="clientlocation"),
    path('doctor/', ClientDoctorView.as_view(), name="clientdoctor"),
    path('search/', ClientSearchView.as_view(), name="clientsearch"),
    path('my-appointment/doctor/', ClientAppointementShowView.as_view(), name="clientappointmentlist"),
    path('appointment/', ClientAppointmentCreateView.as_view(), name="clientappointment"),
    path('makeappointment/<int:id>/', MakeAppointment, name="makeappointment"),
    path('saveappointment/<int:id>/', saveAppointment, name="saveappointment"), 
    path('contact/', ClientContactView.as_view(), name="clientcontact"),
    path('login/', ClientLoginView.as_view(), name="clientlogin"),
    path('registration/', ClientRegistrationView.as_view(), name="clientregistration"),
    path('logout/', ClientLogoutView.as_view(), name="logout"),




    # admin
    path('hospital-admin/', AdminHomeView.as_view(), name="adminhome"),
    path('hospital-admin/table/', AdminTableView.as_view(), name="admintable"),
    path('hospital-admin/slider/list/',
         AdminSliderListView.as_view(), name="adminsliderlist"),
    path('hospital-admin/slider/create/',
         AdminSliderCreateView.as_view(), name="adminslidercreate"),
    path('hospital-admin/slider/<int:pk>/update/',
         AdminSliderUpdateView.as_view(), name="adminsliderupdate"),
    path("hospital-admin/slider/<int:pk>/delete/",
         AdminSliderDeleteView.as_view(), name="adminsliderdelete"),
    path('hospital-admin/doctor/list/',
         AdminDoctorListView.as_view(), name="admindoctorlist"),
    path("hospital-admin/doctor/create",
         AdminDoctorCreateView.as_view(), name="admindoctorcreate"),
    path('hospital-admin/doctor/<int:pk>/update/',
         AdminDoctorUpdateView.as_view(), name="admindoctorupdate"),
    path("hospital-admin/doctor/<int:pk>/delete/",
         AdminDoctorDeleteView.as_view(), name="admindoctordelete"),
    path('hospital-admin/login/', AdminLoginView.as_view(), name="adminlogin"),
    path('hospital-admin/logout/', AdminLogoutView.as_view(), name="adminlogout"),
    path('hospital-admin/register/', AdminRegistrationView.as_view(), name="adminregistration"),
    path('hospital-admin/appointment/list/',
         AdminAppointmentView.as_view(), name="adminappointment"),
     path('hospital-admin/appointment/list-urgent/',
         AdminAppointmentUrgentView.as_view(), name="adminappointmenturgent"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospitalproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospitalapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/clienttemplates/appointdoctor.html
{% extends 'clienttemplates/clientbase.html' %} 
{% load static %} 
{% block content %}
<div class="card mx-auto mt-4" style="width: 24rem">
    <div class="card-header">
        <strong class="lead">Welcome to Login</strong>
    </div>
    <div class="card-body mt-n3">
        <!-- main-heading -->
        <h2 class="main-title-w3layouts mb-2 text-center text-white">
            Make Appointment
        </h2>

        <!--         	{% if error %}
          <li class="text-danger">password</li>
          {% endif %} -->
        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <button class="btn btn-info w-100 primary">Make Appointment</button>
        </form> -->

        <form  method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <div class="form-group">
                <label for="name">Full Name</label>
                <input type="text" class="form-control" id="name" name='name' placeholder="Enter your fullname...">
              </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Email address</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" name='email' placeholder="name@example.com">
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Phone</label>
              <input type="text" class="form-control" id="exampleFormControlInput1" name='mobile' placeholder="XXX-XXXX-XXX">
            </div>
            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" name="address" placeholder="Enter your street address">
              </div>
            <div class="form-group">
              <label for="exampleFormControlSelect1">select Your Gender</label>
              <select class="form-control" name='gender' id="exampleFormControlSelect1">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
              </select>
            </div>
            <div class="form-group row">
              <label for="example-date-input" class="col-2 col-form-label">Date</label>
              <div class="col-10">
                <input class="form-control" name='date' type="date" value="2011-08-19" id="example-date-input">
              </div>
            </div>
            <div class="form-group row">
              <label for="example-time-input" class="col-2 col-form-label">Time</label>
              <div class="col-10">
                <input class="form-control" name='time' type="time" value="13:45:00" id="example-time-input">
              </div>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Leave your message here</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" name='message' rows="3"></textarea>
            </div>
            <button class="btn btn-info w-100 primary">Make Appointment</button>
          </form>
    </div>
</div>
{% endblock %}



<!-- department = models.ForeignKey(Department, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    gender = models.CharField(max_length=200, choices=GENDER)
    mobile = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    message = models.TextField(null=True, blank=True) -->

templates/clienttemplates/clientappointment.html
{% extends 'clienttemplates/clientbase.html' %} 
{% load static %} 
{% block content %}
<div class="card mx-auto mt-4" style="width: 24rem">
    <div class="card-header">
        <strong class="lead">Welcome to Login</strong>
    </div>
    <div class="card-body mt-n3">
        <!-- main-heading -->
        <h2 class="main-title-w3layouts mb-2 text-center text-white">
            Make Appointment
        </h2>

        <!--         	{% if error %}
          <li class="text-danger">password</li>
          {% endif %} -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <button class="btn btn-info w-100 primary">Make Appointment</button>
        </form>
    </div>
</div>
{% endblock %}

templates/clienttemplates/clientappointmentshow.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Appointment List</h2>
<section class="tables-section">
    <!-- table1 -->

    <div  style="padding: 12px;border:2px solid grey;border-radius: 12px;">
        <div class="outer-w3-agile mt-3"  style="padding: 12px;border:2px solid grey;border-radius: 12px;">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Department</th>
                            <th scope="col">Doctor</th>
                            <!-- <th scope="col">Name</th>
                      <th scope="col">Address</th>
                      <th scope="col">Gender</th>
                      <th scope="col">Mobile</th>
                      <th scope="col">Email</th> -->
                            <th scope="col">Date</th>
                            <th scope="col">Time</th>
                            <th scope="col">Message</th>
                            <!-- <th scope="col">Created at</th> -->
                        </tr>
                    </thead>
                    <tbody>
                        {% for appointment in allappoinments %}

                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{appointment.department}}</td>
                            <td>{{appointment.doctor}}</td>
                            <!-- <td>{{appointment.name}}</td>
                      <td>{{appointment.address}}</td>
                      <td>{{appointment.gender}}</td>
                      <td>{{appointment.mobile}}</td>
                      <td>{{appointment.email}}</td> -->
                            <td>{{appointment.date}}</td>
                            <td>{{appointment.time}}</td>
                            <td>{{appointment.message}}</td>
                            <!-- <td>{{appointment.created_at}}</td> -->
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/clienttemplates/clientbase.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Doctor Recommendation System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Alleviating Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="{% static 'clientstatic/css/bootstrap.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'clientstatic/css/style.css' %}" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="{% static 'clientstatic/css/fontawesome-all.min.css' %}" rel="stylesheet">
    <!-- //Custom Theme files -->
	<link href="{% static 'clientstatic/css/minimal-slider.css' %}" rel='stylesheet' type='text/css' />
	<link rel="stylesheet" href="{% static 'clientstatic/css/flexslider.css' %}" type="text/css" media="screen" property="" />
    <!-- online-fonts -->
	<link href="//fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800,900" rel="stylesheet"><!-- //online-fonts -->
	<style>
		.checkBox{
			display: inline-block;
			width: 30%;
		}
	</style>
	
</head>
<body>
        <!-- header -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-gradient-secondary">
                <h1>
                    <a class="navbar-brand text-white" href="{% url 'hospitalapp:index' %}">
                       DRS System
                    </a>
                </h1>
                <button class="navbar-toggler ml-md-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-lg-auto text-center">
						{% if request.user.is_authenticated %}
							<li class="nav-item active  mr-3 mt-lg-0 mt-3">

								<a class="nav-link" href="{% url 'hospitalapp:index' %}">Home
									<span class="sr-only">(current)</span>
								</a>
							</li>
							
							<li class="nav-item  mr-3 mt-lg-0 mt-3">
								<a class="nav-link" href="{% url 'hospitalapp:clientappointment' %}">Appointment</a>
							</li>	
							
							<li class="nav-item mr-3 mt-lg-0 mt-3">
								<a class="nav-link" href="{% url 'hospitalapp:clientdoctor' %}">Doctors</a>
							</li>

							<li class="nav-item mr-3 mt-lg-0 mt-3">
								<a class="nav-link" href="{% url 'hospitalapp:clientappointmentlist' %}">My Appointment</a>
							</li>

							
							<li class="nav-item">
								<a class="nav-link"  href="/logout">Logout</a>

							</li>
							{% else %}
								<li class="nav-item">
									<a class="nav-link" href="{% url 'hospitalapp:clientlogin' %}">Login</a>      
								</li>
						
								<li class="nav-item">
								<a class="nav-link" href="{% url 'hospitalapp:clientregistration' %}">Sign Up</a>      
								</li>
						  {% endif %}	


                    </ul>
                </div>
            </nav>
        </header>

{% block content %}


{% endblock %}
{% block js %}


{% endblock %}
<footer class="py-sm-5">
		<div class="container">
			<div class="row py-5">
				<!-- footer grid1 -->
				<div class="col-lg-3 col-sm-6 fv5-contact">
					<h2 class="mb-4">Contact Us</h2>
					<div class="fv3-contact mt-3">
					
						<span class="fas fa-home mr-2"></span>
						<p>Uk</p>
					</div>
					
					<div class="fv3-contact mt-3">
						<span class="fas fa-envelope-open mr-2"></span>
						<a href="mailto:info@doctorrecomendation.com" class="text-secondary">info@doctorrecomendation.com</a>
					</div>
				</div>
				<!-- //footer grid1 -->
				<!-- footer grid2 -->
				<div class="col-lg-3  col-sm-6 footv3-left text-lg-center my-sm-0 mt-5">
					<h3 class="mb-4">Opening Hours</h3>
					<ul class="list-agileits">
						<li>
							Mon – Fri ------- 09:00-17:00
						</li>
						<li class="my-3">
							Saturday -------- 09:30-17:00</a>
						</li>
						<li class="mb-3">
							Sunday ---------- 10:30-18:00
						</li>
						
					</ul>
				</div>
				<!-- //footer grid2 -->
				<!-- footer grid3 -->
				<div class="col-lg-3  col-sm-6 footv3-left text-lg-center my-lg-0 mt-sm-5 mt-5">
					<h3 class="mb-4">Navigation</h3>
					<ul class="list-agileits">
						<li>
							<a href="">
								Home
							</a>
						</li>
						
					</ul>
				</div>
				<!-- //footer grid3 -->
				<!-- footer grid4  -->
				<div class="col-lg-3  col-sm-6 footv3-left my-lg-0 mt-5">
					<h3 class="mb-4">subscribe to newsletter</h3>
					<form action="#" method="post">
						<div class="form-group">
							<input type="email" class="form-control  bg-dark border-0" id="email" placeholder="Enter email" name="email" required>
						</div>
						<div class="form-group">
							<input type="Submit" class="form-control bg-secondary text-white border-0" id="sub" value="submit" name="sub">
						</div>
					</form>
				</div>
				<!-- //footer grid4 -->
			</div>
			<div class="cpy-right text-center  pt-3">
				
				<div class="copyrightbottom">
					<p class="text-secondary">© 2021 Alleviating. All rights reserved
						
					</p>
				</div>
				<div class="copyrighttop">
					<ul>
						<li>
							<h4>Follow us on:</h4>
						</li>
						<li>
							<a class="facebook" href="#">
								<i class="fab fa-facebook-f"></i>
							</a>
						</li>
						<li>
							<a class="facebook" href="#">
								<i class="fab fa-twitter"></i>
							</a>
						</li>
						<li>
							<a class="facebook" href="#">
								<i class="fab fa-google-plus-g"></i>
							</a>
						</li>
						<li>
							<a class="facebook" href="#">
								<i class="fab fa-pinterest-p"></i>
							</a>
						</li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<!-- //footer container -->
	</footer>
    <script src="{% static 'clientstatic/js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
	<script src="{% static 'clientstatic/js/minimal-slider.js' %}"></script>
<!-- flexSlider (for testimonials) -->
		<!-- Calendar -->
				<link rel="stylesheet" href="css/jquery-ui.css" />
				<script src="{% static 'clientstatic/js/jquery-ui.js' %}"></script>
				  <script>
						  $(function() {
							$( "#datepicker" ).datepicker();
						  });
				  </script>
				<!-- //Calendar -->

	<script defer src="{% static 'clientstatic/js/jquery.flexslider.js' %}"></script>
	<script>
		$(window).load(function () {
			$('.flexslider').flexslider({
				animation: "slide",
				start: function (slider) {
					$('body').removeClass('loading');
				}
			});
		});
	</script>
	<!-- //flexSlider (for testimonials) -->

    <!-- script for password match -->
    <script>
        window.onload = function () {
            document.getElementById("password1").onchange = validatePassword;
            document.getElementById("password2").onchange = validatePassword;
        }

        function validatePassword() {
            var pass2 = document.getElementById("password2").value;
            var pass1 = document.getElementById("password1").value;
            if (pass1 != pass2)
                document.getElementById("password2").setCustomValidity("Passwords Don't Match");
            else
                document.getElementById("password2").setCustomValidity('');
            //empty string means no validation error
        }
    </script>
    <!-- script for password match -->
    <!-- start-smooth-scrolling -->
    <script src="{% static 'clientstatic/js/move-top.js' %}"></script>
    <script src="{% static 'clientstatic/js/easing.js' %}"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();

                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 1000);
            });
        });
    </script>
    <!-- //end-smooth-scrolling -->
    <!-- smooth-scrolling-of-move-up -->
    <script>
        $(document).ready(function () {
            /*
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear' 
            };
            */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <script src="{% static 'clientstatic/js/SmoothScroll.min.js' %}"></script>
    <!-- //smooth-scrolling-of-move-up -->
    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'clientstatic/js/bootstrap.js' %}"></script>	

templates/clienttemplates/clientcontact.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}
<div class="form-group">
 
  <div class="about">
    <div class="abt-layer">
        <div class="container">
            <div class="about-main">
                <div class="about-right">
                    <h3 class="subheading-w3-agile">Make an Contact</h3>
                    <div class="form-control">
                      <form method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button>Submit</button>
                        
                     </form>
                    </div>
            </div>
        </div>
     </div>
  
</div>  
    <!-- //contact -->
    <!-- map -->
    <div class="map px-2">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3533.9922225621376!2d85.3195394142343!3d27.655712334367948!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb177ecff27973%3A0xb57b2fbfc94f7fe7!2sSarobar%20Technology%20Pvt.%20Ltd.!5e0!3m2!1sen!2snp!4v1571133210098!5m2!1sen!2snp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
{% endblock %}

templates/clienttemplates/clientdoctor.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}
<div class="about">
	<div class="abt-layer">
		<div class="container">
				
			<h3 class="text-center" class="text-success">Doctor List</h3><br>
					<!-- <i class='fas fa-file-medical-alt'></i> -->
			<i class="fa fa-bus" aria-hidden="true"></i>
<form method="GET">
	<div class="row">
	  	<div class="col-md-3">
	    	<select class="form-control" name="department">
	    		{% for dep in departments %}
				<option value="{{dep.title}}">{{dep.title}}</option>
	    		{% endfor %}
			</select>
	  	</div><br>
	  	<div class="col-md-3">
	   		<input class="form-control" type="text" placeholder="Search" name="name" aria-label="Search">
	  	</div>
	  	<div class="col-md-3">
	  		<button class="btn btn-info">Search</button>
	  	</div>
	</div>
</form>

<div class="row"> 
{% for doctor in doctors %}
    <div class="col-md-4 mt-2" >
	    <!-- <div class="shadow-none mb-4 style="background-color: #C7E3FF>  -->
		    <img src="{{doctor.image.url }}" class="img-fluid" style="height: 250px;width: 400px; object-fit: cover;">
		    <h3 class="text-center">{{doctor.name}}</h3>
		    <p class="text-center">{{doctor.department|truncatewords:"5"}}</p>
<!-- 		    <p>Speciapty:{{doctors.speciapty}}</p>                
		    <p>Quapfication:{{doctors.quapfication|truncatewords:"3"}}</p>
		    <p>Email{{doctors.email}}</p>
	       	<p>Experience{{doctors.experience|truncatewords:"5"}}</p>
		    <p>About{{doctors.about|truncatewords:"5"}}</p> -->
		<!-- </div> -->    
		   
    </div> 
{% endfor %}

</div>
</div>
</div>

{% endblock %}


{% block js %}
<script>
  $(document).ready(function () {
      $('select').selectize({
          sortField: 'text'
      });
  });
</script>  
{% endblock %}

templates/clienttemplates/clientsearch.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

 <h3>Search Results</h3>

 {% for blog in results %}

 <li> <a href="{% url 'hospitalapp:clientdoctor' %}">{{alldoctor.name}}</a></li> 

 {% empty %}
 <li>no results found.....</li>
{% endfor %}

{% endblock %}

templates/clienttemplates/login.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<div class="card mx-auto mt-4" style="width: 24rem">
    <div class="card-header">
        <strong class="lead">Welcome to Login</strong>
    </div>
    <div class="card-body mt-n3">
        <!-- main-heading -->
        <h2 class="main-title-w3layouts mb-2 text-center text-white">Login</h2>

        <!--         	{% if error %}
            <li class="text-danger">password</li>
            {% endif %} -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <button class="btn btn-info w-100 primary">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/clienttemplates/mylocation.html
<!DOCTYPE html>
<html>
<head>
  <style>
    /* Set the size of the div element that contains the map */
    #map {
      height: 400px;  /* The height is 400 pixels */
      width: 100%;  /* The width is the width of the web page */
    }
  </style>
</head>
<body>
  <h3>My Google Maps Demo</h3>
  <button onclick="getLocation()">Show my position on map</button>
  <!--The div element for the map -->
  <div id="map"></div>



  <script>

    function getLocation() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
      } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
      }
    }

    function showPosition(position) {
      var lat = position.coords.latitude;
      var long = position.coords.longitude;
 
    var myloc = {
      lat: lat,
      lng: long
    };
  // The map, centered at Uluru
  var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 15, center: myloc});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: myloc, map: map});
}
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDvhmMEMeef2PTgwp_lHDwdrR1289D2Ws">
</script>
</body>
</html>

templates/clienttemplates/recommendation.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}


<div class="about">
  <div class="abt-layer">
    <div class="container" style="margin-bottom: 50px;">
      
      <div class="row">
        <div class="container">
          <div class="jumbotron">
        <label>Dear Patients as per your symptoms</label><br>
        <label>Your Test Result for Covit-19 is {{result}}</label><br>
        <label>Your Test Result for Diabetes is 
          {{diab}}
        </label><br>
        <label>Please make appointment with the doctors we recommend</label>
      </div>
      </div>
      </div>
      
      <div class="row">
        {% for doctor in doctors %}
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Dr.{{doctor.name}}</h5>
              <p class="card-text">{{doctor.about}}</p>
              <p class="card-text">Distance {{doctor.dist }} K.M</p
              <a href="{% url 'hospitalapp:makeappointment' doctor.id %}" class="btn btn-primary">Make Appointment</a>
            </div>
          </div>
        </div>
        {% endfor %}

        <div class="col-12" >
          {{ my_map|safe }}
        </div>
        
      </div>
      
      
    </div>
  </div>
</div>

{% endblock %}  

templates/clienttemplates/registration.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<div class="card mx-auto mt-4" style="width: 24rem">
    <div class="card-header">
        <strong class="lead">Welcome to Login</strong>
    </div>
    <div class="card-body mt-n3">
        <!-- main-heading -->
        <h2 class="main-title-w3layouts mb-2 text-center text-white">
            Registration
        </h2>

        <!--         	{% if error %}
            <li class="text-danger">password</li>
            {% endif %} -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <button class="btn btn-info w-100 primary">Registration</button>
        </form>
    </div>
</div>
{% endblock %}

templates/clienttemplates/services.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services</title>
</head>
<body>
    
</body>
</html>

templates/clienttemplates/success.html
{% extends 'clienttemplates/clientbase.html' %} 
{% load static %} 
{% block content %}
<div class="card mx-auto mt-4" style="width: 24rem">
    <div class="card-header">
        <strong class="lead">Appointment Success</strong>
    </div>
    <div class="card-body mt-n3">
        
    </div>
</div>
{% endblock %}



<!-- department = models.ForeignKey(Department, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    gender = models.CharField(max_length=200, choices=GENDER)
    mobile = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    message = models.TextField(null=True, blank=True) -->