hospitalapp/urls.py
from django.urls import path
from .views import *

app_name = 'hospitalapp'
urlpatterns = [
    # clients
#     path('', HomeView.as_view(), name="index"),
    path('', HomeView, name="index"),
    path('recommend-doctor/', RecommendDoctorView.as_view(), name="recommend"),
    path('cliendhome', ClientHomeView.as_view(), name="clienthome"),
    path('my-loc/', ClientLocationView.as_view(), name="clientlocation"),
    path('doctor/', ClientDoctorView.as_view(), name="clientdoctor"),
    path('search/', ClientSearchView.as_view(), name="clientsearch"),
    path('my-appointment/doctor/', ClientAppointementShowView.as_view(), name="clientappointmentlist"),
    path('appointment/', ClientAppointmentCreateView.as_view(), name="clientappointment"),
    path('makeappointment/<int:id>/', MakeAppointment, name="makeappointment"),
    path('saveappointment/<int:id>/', saveAppointment, name="saveappointment"), 
    path('contact/', ClientContactView.as_view(), name="clientcontact"),
    path('login/', ClientLoginView.as_view(), name="clientlogin"),
    path('registration/', ClientRegistrationView.as_view(), name="clientregistration"),
    path('logout/', ClientLogoutView.as_view(), name="logout"),




    # admin
    path('hospital-admin/', AdminHomeView.as_view(), name="adminhome"),
    path('hospital-admin/table/', AdminTableView.as_view(), name="admintable"),
    path('hospital-admin/slider/list/',
         AdminSliderListView.as_view(), name="adminsliderlist"),
    path('hospital-admin/slider/create/',
         AdminSliderCreateView.as_view(), name="adminslidercreate"),
    path('hospital-admin/slider/<int:pk>/update/',
         AdminSliderUpdateView.as_view(), name="adminsliderupdate"),
    path("hospital-admin/slider/<int:pk>/delete/",
         AdminSliderDeleteView.as_view(), name="adminsliderdelete"),
    path('hospital-admin/doctor/list/',
         AdminDoctorListView.as_view(), name="admindoctorlist"),
    path("hospital-admin/doctor/create",
         AdminDoctorCreateView.as_view(), name="admindoctorcreate"),
    path('hospital-admin/doctor/<int:pk>/update/',
         AdminDoctorUpdateView.as_view(), name="admindoctorupdate"),
    path("hospital-admin/doctor/<int:pk>/delete/",
         AdminDoctorDeleteView.as_view(), name="admindoctordelete"),
    path('hospital-admin/login/', AdminLoginView.as_view(), name="adminlogin"),
    path('hospital-admin/logout/', AdminLogoutView.as_view(), name="adminlogout"),
    path('hospital-admin/register/', AdminRegistrationView.as_view(), name="adminregistration"),
    path('hospital-admin/appointment/list/',
         AdminAppointmentView.as_view(), name="adminappointment"),
     path('hospital-admin/appointment/list-urgent/',
         AdminAppointmentUrgentView.as_view(), name="adminappointmenturgent"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospitalproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospitalapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminappointment.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Appointment List</h2>
<section class="tables-section">


	<!-- table1 -->
	

<div class="outer-w3-agile mt-3">
  <div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Department</th>
				<th scope="col">Doctor</th>
				<th scope="col">Name</th>
				<th scope="col">Address</th>
				<th scope="col">Gender</th>
				<th scope="col">Mobile</th>
				<th scope="col">Email</th>
				<th scope="col">Date</th>
				<th scope="col">Time</th>
				<th scope="col">Message</th>
				<th scope="col">Created at</th>
						
			</tr>
		</thead>
	<tbody>
		{% for appointment in allappoinments %}

            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{appointment.department}}</td>
                <td>{{appointment.doctor}}</td>
                <td>{{appointment.name}}</td>
                <td>{{appointment.address}}</td>
                <td>{{appointment.gender}}</td>
                <td>{{appointment.mobile}}</td>
                <td>{{appointment.email}}</td>
                <td>{{appointment.date}}</td>
                <td>{{appointment.time}}</td>
                <td>{{appointment.message}}</td>
                <td>{{appointment.created_at}}</td>

            </tr>


                   

	{% endfor %}
	</tbody>
</table>
</div>




</div>
</section>




{% endblock %}

templates/admintemplates/adminappointmenturgent.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content%}
<h2 class="main-title-w3layouts mb-2 text-center">Urgent Appointment List</h2>
<section class="tables-section">
    <!-- table1 -->

    <div class="outer-w3-agile mt-3">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Department</th>
                        <th scope="col">Doctor</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Mobile</th>
                        <th scope="col">Email</th>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                        <th scope="col">Message</th>
                        <th scope="col">Created at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for appointment in allappoinments %}

                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{appointment.department}}</td>
                        <td>{{appointment.doctor}}</td>
                        <td>{{appointment.name}}</td>
                        <td>{{appointment.address}}</td>
                        <td>{{appointment.gender}}</td>
                        <td>{{appointment.mobile}}</td>
                        <td>{{appointment.email}}</td>
                        <td>{{appointment.date}}</td>
                        <td>{{appointment.time}}</td>
                        <td>{{appointment.message}}</td>
                        <td>{{appointment.created_at}}</td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock %}

templates/admintemplates/admindoctorcreate.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Doctor List</h2>
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<!-- <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4> -->
		<h4>Doctor Form</h4>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<br>
			<button class="btn btn-info w-50">Submit Data</button>
		</form>
	</div>
</section>

{% endblock %}

templates/admintemplates/admindoctordelete.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Doctor Delete</h2>
<!-- Tables content -->
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<!-- <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4> -->
		<h4>Doctor Delete</h4>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<h4>Are you sure to delete {{object.name}}?</h4>
			<br>
			<button class="btn btn-danger">Yes</button>
			<a class="btn btn-info" href="{% url 'hospitalapp:admindoctorlist' %}">No</a>
		</form>
	</div>
</section>

{% endblock %}

templates/admintemplates/admindoctorlist.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Doctor List</h2>

<!-- Tables content -->
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<!-- <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4> -->
		<a href="{% url 'hospitalapp:admindoctorcreate' %}" style="float: right;color: tomato;">Add new doctor</a>
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Name</th>
						
						<th scope="col">Department</th>
						<th scope="col">Speciality</th>
						<th scope="col">Qualification</th>
						<th scope="col">Image</th>
						<th scope="col">Email</th>
						<th scope="col">Experience</th>
						<th scope="col">Created at</th>
						
					</tr>
				</thead>
			<tbody>
               {% for doctor in doctorsall %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{doctor.name}}</td>
		                
		                <td>{{doctor.department}}</td>
		                <td>{{doctor.speciality}}</td>
		                <td>{{doctor.qualification}}</td>
		                <td><img src="{{doctor.image.url }}" width="100"></td>
		                <td>{{doctor.email}}</td>
		                <td>{{doctor.experience}}</td>
		                <td>{{doctor.created_at}}</td>
					
				
                        <td>
	               	      <a class="btn btn-info" href="{% url 'hospitalapp:admindoctorupdate' doctor.id %}">Update</a>

					     <a class="btn btn-danger" href="{% url 'hospitalapp:admindoctordelete' doctor.id %}">Delete</a>
				        </td>
                    </tr>
               {% endfor %}
		    </tbody>
		</table>
	</div>
</div>
	<!--// table7 -->
	
</section>


{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
 <div class="container-fluid">
     Welcome
 </div>              
 
{% endblock %}

templates/admintemplates/adminlogin.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<div class="bg-page py-5">
        <div class="container">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Login</h2>
            <!--// main-heading -->
            <div class="form-body-w3-agile text-center w-lg-50 w-sm-75 w-100 mx-auto mt-5">
                
                    <div class="form-group">
                    	{% if error %}
		                <li class="text-danger">{{error}}</li>
		                {% endif %}
		                <form method="POST">
			             {% csrf_token %}
			             {{ form.as_p }}
		                 <button class="btn btn-info w-75 primary">Login</button>

		                </form>	
		                
		            </div>
		        
		    </div>
		</div>
</div>


{% endblock %}

templates/admintemplates/adminregistration.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}

<div class="bg-page py-5">
        <div class="container">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Register</h2>
            <!--// main-heading -->
            <div class="form-body-w3-agile text-center w-lg-50 w-sm-75 w-100 mx-auto mt-5">
                
                    <div class="form-group">
                    	{% if error %}
		                <li class="text-danger">{{error}}</li>
		                {% endif %}
		                <form method="POST">
			             {% csrf_token %}
			             {{ form.as_p }}
		                 <button class="btn btn-info w-75 primary">Signup</button>

		                </form>
		            </div>
		        
		    </div>
		</div>
</div>
{% endblock %}

templates/admintemplates/adminslidercreate.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Slider Form</h2>
<!-- Tables content -->
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<!-- <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4> -->
		<h4>Slider Form</h4>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<br>
			<button class="btn btn-info w-50">Submit Data</button>
		</form>
	</div>
</section>
{% endblock %}

templates/admintemplates/adminsliderdelete.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Slider Delete</h2>
<!-- Tables content -->
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<!-- <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4> -->
		<h4>Slider Delete</h4>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<h4>Are you sure to delete {{object.title}}?</h4>
			<br>
			<button class="btn btn-danger">Yes</button>
			<a class="btn btn-info" href="{% url 'hospitalapp:adminsliderlist' %}">No</a>
		</form>
	</div>
</section>
{% endblock %}

templates/admintemplates/adminsliderlist.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Slider List</h2>
<!-- Tables content -->
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<!-- <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4> -->
		<a href="" style="float: right;color: tomato;">Add new slider</a>
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Title</th>
						<th scope="col">Caption</th>
						<th scope="col">Image</th>
						<th scope="col">Created at</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					{% for slider in sliderlist %}
					<tr>
						<th scope="row">{{forloop.counter}}</th>
						<td>{{slider.title}}</td>
						<td>{{slider.caption}}</td>
						<td><img src="{{slider.image.url}}" width="100"></td>
						<td>{{slider.created_at}}</td>
						<td>
							<a class="btn btn-info" href="{% url 'hospitalapp:adminsliderupdate' slider.id %}">Update</a>
							<a class="btn btn-danger" href="{% url 'hospitalapp:adminsliderdelete' slider.id %}">Delete</a>
							<a class="btn btn-danger" href="{% url 'hospitalapp:adminslidercreate' %}">Create</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<!--// table7 -->
	
</section>


{% endblock %}

templates/admintemplates/admintable.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}
<h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
<!-- Tables content -->
<section class="tables-section">
	<!-- table1 -->
	

	<div class="outer-w3-agile mt-3">
		<h4 class="tittle-w3-agileits mb-4">Responsive Table</h4>
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
						<th scope="col">Heading</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">1</th>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
					</tr>
					<tr>
						<th scope="row">2</th>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
					</tr>
					<tr>
						<th scope="row">3</th>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
						<td>Cell</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<!--// table7 -->
	
</section>


{% endblock %}